### ISSUE TITLE
No ‘Access-Control-Allow-Origin’ header

### ISSUE THREAD

**Issue by sparkadal** [start-angular/SB-Admin-BS4-Angular-5#119]
Morning 
first of all thanks about your works
I'm working on Symfony API  back-end  and  used Angular in Front-end.
when I try to sent request  with header  I get response 401 and No access-Control-Allow-Origin
how can I fixed it?
best regards

**Comment by nitinkumarmishra** [comment]
sorry for the late reply 401 means unauthorized request you need to added token via interceptors.
Adding interceptor in quite simple in angular > 4.3.0 refer docs 
https://angular.io/guide/http#advanced-usage

**Comment by alpesh-patel93** [comment]
Make sure you have enabled CORS in the backend. 
Closing the issue for now. Please reopen if you still found the problem.
