### ISSUE TITLE
How do we login, logout on mobile device or tablet

### ISSUE THREAD

**Issue by stherrienaspnet** [start-angular/SB-Admin-BS4-Angular-5#120]
Your template is amazing! I really appreciate the your gift to the community :) It would be nice to be able to login and logout using a phone or tablet device. I know you are limited on space when on mobile, an idea could be to remove the text 'SB Admin BS 4 Angular4' and replace it by an Home link icon. This should give some room to login menu...

Wonderfull work!

**Comment by nitinkumarmishra** [comment]
Sure will try your suggestion and will add it in next release

**Comment by alpesh-patel93** [comment]
Logout and other option added on sidebar for mobile/small screens.
