### ISSUE TITLE
RTL problem with breadcrumb

### ISSUE THREAD

**Issue by webnegar** [start-angular/SB-Admin-BS4-Angular-5#121]
hi,
in RTL mode [page-header.component.html] remains in LTR,
it can be corrected with this style:

`.breadcrumb-item {
    float: right;
}
`
or some corrections in 
src\styles\bootstrap\_breadcrumb.scss

please add it.
best regards

**Comment by nitinkumarmishra** [comment]
sure will add it in release

**Comment by alpesh-patel93** [comment]
It's fixed now, Closing.

**Comment by RedMoonLight** [comment]
I want the text to start from the right in the rtl mode. how can i do it?
