### ISSUE TITLE
Some corrections in RTL mode

### ISSUE THREAD

**Issue by webnegar** [start-angular/SB-Admin-BS4-Angular-5#122]
hi,
according to attached picture, some corrections for RTL mode needed.

![corrections-rtl](https://user-images.githubusercontent.com/7112978/29257958-27e97896-80cb-11e7-91a5-d2f5d8632aa4.jpg)

best regards

**Comment by sanketsahusoft** [comment]
@webnegar Can you please fix that and send a pull-request. We are too occupied to fix that at the moment.

**Comment by alpesh-patel93** [comment]
Fixed many RTL issues, Closing it for now. Please reopen if anyone found more RTL issues.
