### ISSUE TITLE
Update to Bootstrap 4.0.0-beta

### ISSUE THREAD

**Issue by bigadz** [start-angular/SB-Admin-BS4-Angular-5#124]
Could you please update with Bootstrap 4.0.0-beta?

Thanks.

**Comment by dosser66** [comment]
I upgraded to Bootstrap 4.0.0-beta but I noticed the header is not rendering correctly.  Is there something I'm missing?  Thx.

**Comment by dosser66** [comment]
Nevermind.  Bootstrap upgraded to 4.0.0-beta but a lot of the style classes changed a lot so it's just a matter of reading the manual. ^_^

**Comment by nitinkumarmishra** [comment]
I updated the application in bootstrap4.0.0 beta and 5.0.0-rc.0, will push it soon, thanks

**Comment by bigadz** [comment]
Sweet. Thanks.

**Comment by INGCRENGIFO** [comment]
Super!

**Comment by solenovex** [comment]
Thanks!

**Comment by alpesh-patel93** [comment]
Bootstrap is now upgraded to the latest v4.0.0-beta.3.
