### ISSUE TITLE
Dropdown is not working

### ISSUE THREAD

**Issue by spiderhc** [start-angular/SB-Admin-BS4-Angular-5#131]
Dropdown is not opening when clicked. 
Don't need to clone this repo to test, just see online Demo.

Has anyone solved this problem?

**Comment by nitinkumarmishra** [comment]
Please add a screenshot, thanks

**Comment by rahulva** [comment]
It works for me. Could you share any specifics or screenshot if the issue still persist?

**Comment by alpesh-patel93** [comment]
Closing the issue for now. Kindly share the screenshot if it still persists.
