### ISSUE TITLE
Want to navigate to next component from the button which is in the dashboard container not in header,sidebar & footer.

### ISSUE THREAD

**Issue by deepaknouliya** [start-angular/SB-Admin-BS4-Angular-5#162]
Want to navigate to next component from the button which is in the dashboard container not in header,sidebar & footer.

**Comment by alpesh-patel93** [comment]
The issue is not clear. You can use `[routerLink]="['/path']"` in button tag to navigate to any route, Thanks.

**Comment by alpesh-patel93** [comment]
Closing this for now, Please reopen the issue with explanation if you find any problem.
