### ISSUE TITLE
Angular 5 Version

### ISSUE THREAD

**Issue by avilao** [start-angular/SB-Admin-BS4-Angular-5#163]
Hello

Are there plans to upgrade this to Angular 5?

Thank you

**Comment by fabiomartino** [comment]
Hi I made a PR https://github.com/start-angular/SB-Admin-BS4-Angular-4/pull/144
and "gradually" update and upgrade this project to Angular 4.4.6 and the CLI to 1.4.9.
On my local workspace I upgrade all (Angular & CLI) to version 5 (CLI is 1.5.0) with out problem...
So I think is a question of time for the maintainer of this project to merge the pending Pulls Request and then switch to this new major version of Angular.

**Comment by fabiomartino** [comment]
I add one more commit to my previus PL https://github.com/start-angular/SB-Admin-BS4-Angular-4/pull/144/commits/a3f8f7d2cd4b958a70fb7c271ede1d9e571a10cb
and include the needed changes for package.json

**Comment by nitinkumarmishra** [comment]
Done with the upgrade to angular5.0.1 and bootstrap 4.0.0-beta-2
