### ISSUE TITLE
Sidebar html is invalid (missing <li>)?

### ISSUE THREAD

**Issue by chetski** [start-angular/SB-Admin-BS4-Angular-5#164]
Just looking at the sidebar.html file and the HTML is invalid as we have <a> tags directly under a &lt;ul&gt;. I believe the only element allowed under a &lt;ul&gt; is &lt;li&gt;??

    <ul class="list-group">
        <a routerLink="/dashboard" [routerLinkActive]="['router-link-active']" class="list-group-item">
            <i class="fa fa-fw fa-dashboard"></i>&nbsp;{{ 'Dashboard' | translate }}
        </a>

**Comment by nitinkumarmishra** [comment]
Can you please fix that and send a pull-request

**Comment by chetski** [comment]
See pull request #165

**Comment by alpesh-patel93** [comment]
Merged.
