### ISSUE TITLE
@ng-bootstrap/ng-bootstrap@1.0.0-beta.5 not compatible with angular 5

### ISSUE THREAD

**Issue by ankitparmar372** [start-angular/SB-Admin-BS4-Angular-5#178]
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN ng-bootstrap/ng-bootstrap@1.0.0-beta.5 requires a peer of @angular/core@^4.0.3 but none was installed.
npm WARN ng-bootstrap/ng-bootstrap@1.0.0-beta.5 requires a peer of @angular/common@^4.0.3 but none was installed.
npm WARN ng-bootstrap/ng-bootstrap@1.0.0-beta.5 requires a peer of @angular/forms@^4.0.3 but none was installed.

**Comment by fabiomartino** [comment]
Hi I made a specific commit in my last PR https://github.com/start-angular/SB-Admin-BS4-Angular-5/pull/172/commits/0aa97c8dab9fb63625acb7c4953466fe0a28d3a3
where the ng-bootstrap as been updated to rev beta.7

**Comment by alpesh-patel93** [comment]
Upgraded angular, bootstrap and ng-bootstrap to their latest version 5.0.1, v4.0.0-beta.3 and v1.0.0-beta.8 respectively.
