### ISSUE TITLE
webpack should not be included in the dev dependencies

### ISSUE THREAD

**Issue by FritzHerbers** [start-angular/SB-Admin-BS4-Angular-5#179]
I hit the following error:
`No module factory available for dependency type: ContextElementDependency`

caused my mismatches in webpack
```
npm ls webpack
+-- @angular/cli@1.5.0
| `-- webpack@3.8.1
`-- webpack@3.9.1
```

https://github.com/start-angular/SB-Admin-BS4-Angular-5/issues/176 installed webpack to the dev dependencies.

angular/cli has itself a dependency to webpack with a specific version and should not be installed.
See https://github.com/angular/angular-cli/issues/6417#issuecomment-315708400

Check that angular/cli is correct global and local, see https://github.com/angular/angular-cli#updating-angular-cli
Also remove node_modules and especially package-lock.json and do a npm install.

**Comment by alpesh-patel93** [comment]
Removed webpack from dev-dependencies in package.json.
