### ISSUE TITLE
app-stat label translate

### ISSUE THREAD

**Issue by giulianozor** [start-angular/SB-Admin-BS4-Angular-5#184]
Hello,
 I'm sorry for the noob question... I'm surely missing something obvious, but is it possible to translate the [label] for the app-stat directive ?

I'd like to have something like

`<app-stat [bgClass]="'primary'" [icon]="'fa-users'" [label]="'users'|translate" ></app-stat>`

I tried to add the ngx-translate imports to the shared/modules/stat, but I can't get it to work and I would like to not configure the available languages in every module I might use :)

thanks

**Comment by alpesh-patel93** [comment]
@giulianozor  Can you please check if you have imported the `TranslateModule` in the module you are using <app-stat></app-stat>, Like in this case `dashboard` module?

**Comment by giulianozor** [comment]
Actually I did modify the component and added some features (added the | translate to the label bind and other minor things)

**Comment by alpesh-patel93** [comment]
Yes, It requires importing the `TranslateModule` in the imports section in order to use the `| translate` pipe in your module.
