### ISSUE TITLE
Why dist directory is not ignored?

### ISSUE THREAD

**Issue by babakyakhchali** [start-angular/SB-Admin-BS4-Angular-5#185]
Hi
Is there any reason for not ignoring dist directory? because after cloning and running npm install and npm start this directory is removed and git shows many changes related to files removed from dist directory?

**Comment by fabiomartino** [comment]
Hi already made a commit in my latest PR https://github.com/start-angular/SB-Admin-BS4-Angular-5/pull/172/commits/6617908cb7d70e7eb2c380ba18a598dd62fdc56f

**Comment by alpesh-patel93** [comment]
Updates git ignore file, Closing the issue.
