### ISSUE TITLE
dist folder disappeared and therefore the demo is not working

### ISSUE THREAD

**Issue by bb1** [start-angular/SB-Admin-BS4-Angular-5#189]
It's a very minor thing, but if someone has push access it would be very nice if he could just build and push the /dist/ folder again.

Thanks! :)

![rawgit_sb_dashboard](https://user-images.githubusercontent.com/3842623/34197274-fd2ad06e-e565-11e7-8cb0-a48f4cbb80d0.PNG)

**Comment by alpesh-patel93** [comment]
Added /dist folder. Demo link is working now.

**Comment by bb1** [comment]
Thanks!
