### ISSUE TITLE
Demo link is not working

### ISSUE THREAD

**Issue by bbeniston** [start-angular/SB-Admin-BS4-Angular-5#190]
Demo link is not working

http://rawgit.com/start-angular/SB-Admin-BS4-Angular-5/master/dist/

**Comment by fabiomartino** [comment]
Yes.. the demo link need an update
ngh work fine for me https://fabiomartino.github.io/SB-Admin-BS4-Angular-5/

**Comment by alpesh-patel93** [comment]
Should be working now.
