### ISSUE TITLE
Error on npm start: Cannot find module 'webpack/lib/node/NodeTemplatePlugin'

### ISSUE THREAD

**Issue by scubed2010** [start-angular/SB-Admin-BS4-Angular-5#207]
I've tried running the project with ng cli 1.5, and I've updated it to the latest cli 1.65, however I still get this error:

Cannot find module 'webpack/lib/node/NodeTemplatePlugin'

Re-installing web pack helps:

npm install --save-dev webpack

However, then I get errors that state app module cannot be found or this:

ERROR in ./src/styles/app.scss
Module build failed: Error: Cannot find module 'node-sass'

Here is ng -v:

Angular CLI: 1.6.5
Node: 8.9.4
OS: win32 x64
Angular: 5.0.1
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

@angular/cli: 1.6.5
@ngtools/json-schema: 1.1.0
typescript: 2.4.2
webpack: 3.10.0

Let me know if you need further info.

**Comment by waleedshkt** [comment]
Had the same issue. But I resolved it by running `npm install webpack --save-dev`
