### ISSUE TITLE
error in error: no ngmodule metadata found for 'appmodule'.

### ISSUE THREAD

**Issue by mmaneff** [start-angular/SB-Admin-BS4-Angular-5#209]
Hi, I have the following issue.

Download the project to my notebook with window 10. I followed the steps necessary to install and run the example but it gave me an error.

First he gave me the error "Can not find module 'webpack / lib / node / NodeTemplatePlugin'". for which install the webpack package.

when I run the example it gives me a new error. Attach the image

![image](https://user-images.githubusercontent.com/11965264/35773322-2beb4d80-092d-11e8-81fa-73a84c494644.png)

Any ideas to solve the new error?

I have the following versions:
.
node 8.6.0
npm 5.3.0
angular / cli 1.6.6

I really like the template. It would be a shame not to be able to use it and have to look for another one.

From already thank you very much

**Comment by mmaneff** [comment]
I have the following versions:
.
node 8.6.0
npm 5.3.0
angular / cli 1.6.6

**Comment by tkd3000** [comment]
I had the same error - this helps for me:

npm remove webpack
npm install --save-dev @angular/cli@latest

**Comment by mmaneff** [comment]
Thanks for answering. Try to execute the command but it gives me the following error.

![image](https://user-images.githubusercontent.com/11965264/35777371-a1339bde-098b-11e8-8fd8-ea1143d34bb3.png)


Maybe he's missing a word to the command.

On the other hand it tells me that I have @ angular / cli version 1.6.7 globally and locally in the project version 1.5.0.

Maybe I have something to do but I'm not sure.

**Comment by liuruomu** [comment]
@mmaneff  I used  npm install --save-dev@latest , not --save-dev  @latest, it works for me

**Comment by clydeburgos** [comment]
Just had this problem of yours..

This solved my problem

npm remove webpack
npm install --save-dev @angular/cli@latest.

https://github.com/angular/angular-cli/issues/8798

**Comment by sparqueur** [comment]
For my part I had to clear npm cache
```
npm cache clean --force
npm install
```

**Comment by pmesserschmidt** [comment]
Remove webpack and manually reinstall reinstall angular/cli. Webpack comes as a part of @angular/cli

`npm remove webpack
npm install --save-dev @angular/cli@latest
`
