### ISSUE TITLE
Refresh page returns 404 or server error

### ISSUE THREAD

**Issue by mavieth** [start-angular/SB-Admin-BS4-Angular-5#217]
Running `npm start` locally seems to not have any problem resolving the URL when the page is refreshed. When compiled and put on a server, refreshing the page results in a 404 or server error.

Any idea how to fix this or how to fix my server redirects would be greatly appreciated!

**Comment by fdelima** [comment]
https://www.youtube.com/watch?v=dlPwcNcMv04

**Comment by nitinkumarmishra** [comment]
just redirect to index.html page
