### ISSUE TITLE
how to add a new nested-menu into the sidebar, but do not let them triggered together.

### ISSUE THREAD

**Issue by LucasMeier** [start-angular/SB-Admin-BS4-Angular-5#221]
Hi, 

In the **sidebar.component.html** I pasted the following **twice**. 

        <div class="nested-menu">
            <a class="list-group-item" (click)="addExpandClass('pages')">
                <span>
                    <i class="fa fa-plus"></i>&nbsp; {{ 'Menu' | translate }}</span>
            </a>
            <li class="nested" [class.expand]="showMenu === 'pages'">
                <ul class="submenu">
                    <li>
                        
                        <a [routerLink]="['/forms']" [routerLinkActive]="['router-link-active']">
                            <span>{{ 'Submenu' | translate }}</span>
                        </a>
                    </li>
                    <li>
                        <a href="javascript:void(0)">
                            <span>{{ 'Submenu' | translate }}</span>
                        </a>
                    </li>
                    <li>
                        <a href="javascript:void(0)">
                            <span>{{ 'Submenu' | translate }}</span>
                        </a>
                    </li>
                </ul>
            </li>
        </div>

The question is : By clicking one menu, both menus are opened. 

In the **sidebar.component.ts** file, the code to control the menu is: 

    addExpandClass(element: any) {
        if (element === this.showMenu) {
            this.showMenu = '0';
        } else {
            this.showMenu = element;
        }
    }

I tried on my own to change the code above, but without success. Could anybody please give me some hint, how to change?

Thanks for the help!

**Comment by nitinkumarmishra** [comment]
just create component and reuse it

**Comment by krishnarm** [comment]
did you mean something like this ?

here is an example for some mat-nav material using angular (http://www.java2s.com/Code/Jar/o/osgi-bundle.htm)

**Comment by zhenfuxu** [comment]
the key word "pages" should replace by other word,should not repeat!
