### ISSUE TITLE
Firebase integration

### ISSUE THREAD

**Issue by sergigrau7** [start-angular/SB-Admin-BS4-Angular-5#66]
Is it possible to integrate Firebase using AngularFire2 as the https://github.com/angular/angularfire2/blob/master/docs/1-install-and-setup.md  description?
When I introduce Setup @NgModule and Inject AngularFire the project doesn't works.

Thanks!

Sergi

**Comment by baldassarreFe** [comment]
Hi, I just tested it quickly and to me everything works fine.

I had another project where I already had a working firebase login service, I just installed firebase and angularfire2, copied my module, added some buttons in the login page and I was good to go.

What kind of errors do you get? Can I help somehow?

**Comment by alpesh-patel93** [comment]
Please go through angularfire's documentation https://github.com/firebase/angularfire. This issue looks more relevant to angularfire rather than this.
Closing the issue for now, Please comment if you find any issue.
